spring:
  application:
    name: web-demo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # 데이터소스 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate  # 스키마 검증만, 변경 안함
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

  # Flyway 마이그레이션 설정
  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    baseline-on-migrate: true   # baseline 기준으로 마이그레이션 가능 - 이전 상태와 충돌날 경우 체크섬 예외 발생
    clean-disabled: true        # clean 명령 비활성화

  # OAuth Client 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
          google:
            client-name: Google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            client-name: Naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# 로깅 설정
logging:
  level:
    org.flywaydb: INFO
    org.springframework.jdbc: INFO
    com.rgs.web_demo: INFO

# 서버 설정
server:
  port: 17070

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpirationMs: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refreshTokenExpirationMs: ${JWT_REFRESH_TOKEN_EXPIRATION}