# 데이터베이스 연결 설정
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rgpsh.iptime.org:5432/web_demo_db
    username: masteruser
    password: masterpass
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 0  # 운영환경에서는 비활성화

  # JPA 마스터 환경 설정
  jpa:
    show-sql: false  # 공통 설정과 동일 (명시적 표시)
    properties:
      hibernate:
        format_sql: false  # 마스터 환경에서는 비활성화
        use_sql_comments: false
        generate_statistics: false

  # Flyway 마스터 환경 설정
  flyway:
    clean-disabled: true  # 마스터환경에서는 clean 금지
    out-of-order: false

  # 보안 설정
  security:
    require-ssl: false  # 필요시 true로 변경

# JWT 마스터 환경 설정 (보안 강화)
jwt:
  secret: "MasterSuperSecretKeyForJwt123456789012345"  # 실제로는 환경변수 사용 권장
  accessTokenExpirationMs: 900000   # 15분 (공통 설정과 동일, 명시적 표시)
  refreshTokenExpirationMs: 604800000  # 7일 (공통 설정과 동일)

# 로깅 설정 (마스터 환경)
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    com.rgs.web_demo: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/web-demo-master.log
    max-size: 10MB
    max-history: 30

# Actuator 마스터 환경 설정 (제한적 노출)
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# 서버 설정 (마스터 환경)
server:
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
  compression:
    enabled: true
  http2:
    enabled: true