spring:
  config:
    import:
      - "optional:file:./config-private/backend/common.properties"
      - "optional:file:./config-private/backend/local.properties"

  # JPA 설정
  jpa:
    show-sql: true  # SQL 로그 출력

  # Flyway 설정
  flyway:
    baseline-on-migrate: false  # 처음부터 마이그레이션
    clean-disabled: false       # clean 허용

# 디버그 로깅
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.rgs.web_demo: DEBUG

app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:4030"