spring:
  datasource:
#    url: jdbc:postgresql://db:5432/web_demo_db
    url: jdbc:postgresql://localhost:5432/web_demo_db
    username: postgres
#    password: 5908
    password: 0000

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8

# JWT 개발 환경 설정
jwt:
  secret: "DevSecretKeyForJwt123456789012345"
  accessTokenExpirationMs: 3600000
  refreshTokenExpirationMs: 2592000000

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.rgs.web_demo: DEBUG