# 데이터베이스 연결 설정
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devdb
    username: devuser
    password: devpass
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # JPA 개발 환경 설정 (공통 설정 덮어쓰기)
  jpa:
    show-sql: true  # 공통은 false, 개발은 true로 덮어쓰기
    properties:
      hibernate:
        format_sql: true  # 공통 설정과 동일하지만 명시적 표시
        use_sql_comments: true  # 개발 환경 추가 설정
        highlight_sql: true

  # Flyway 개발 환경 설정
  flyway:
    clean-disabled: false  # 개발환경에서는 clean 허용

  # 개발 도구
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  #
  security:
    enabled: false

# JWT 개발 환경 설정 (공통 설정 덮어쓰기)
jwt:
  secret: "DevSecretKeyForJwt123456789012345"
  accessTokenExpirationMs: 3600000   # 1시간 (공통 15분 → 개발 1시간)
  refreshTokenExpirationMs: 2592000000  # 30일 (공통 7일 → 개발 30일)

# 로깅 설정 (공통 설정에 추가)
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.rgs.web_demo: DEBUG  # 프로젝트 패키지명에 맞게 수정
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

# Actuator 개발 환경 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 개발환경에서는 모든 엔드포인트 노출
  endpoint:
    health:
      show-details: always
    flyway:
      enabled: true

# 서버 에러 정보 (개발환경)
server:
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always