version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: web-demo-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-devdb}  # devdb로 변경
      POSTGRES_USER: ${DB_USER:-devuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpass}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - ./test-data:/test-data:ro
    networks:
      - web-demo-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-devuser} -d ${DB_NAME:-devdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer-dev:
    image: adminer:latest
    container_name: web-demo-adminer-dev
    ports:
      - "8080:8080"
    environment:
      # Adminer 기본 설정
      ADMINER_DEFAULT_SERVER: postgres-dev
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_USERNAME: devuser
      ADMINER_DEFAULT_DB_NAME: devdb
      # 디자인 테마 (선택사항)
      ADMINER_DESIGN: pepa-linha
    networks:
      - web-demo-dev-network
    depends_on:
      postgres-dev:
        condition: service_healthy
    restart: unless-stopped

networks:
  web-demo-dev-network:
    driver: bridge