name: Deploy Spring Boot Backend

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Backend with Password
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -t -o StrictHostKeyChecking=no skfnx@rgpsh.iptime.org << 'EOF'
            cd /d Z:\workspace\web-demo
            git pull origin master
            gradlew clean bootJar -x test

            cd /d Z:\workspace
            docker-compose up -d --build backend
          EOF
